// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TIMER_H
#define UI_TIMER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Timer
extern void ui_Timer_screen_init(void);
extern void ui_Timer_screen_destroy(void);
extern void ui_event_Timer( lv_event_t * e);
extern lv_obj_t *ui_Timer;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_SetTimerContainer;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_ActiveTimerContainer;
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label23;
// CUSTOM VARIABLES
extern lv_obj_t *uic_a;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

