// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_PokeBallAnalog = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Panel5 = NULL;lv_obj_t *ui_Pil12 = NULL;lv_obj_t *ui_Pil1 = NULL;lv_obj_t *ui_Pil2 = NULL;lv_obj_t *ui_Pil4 = NULL;lv_obj_t *ui_Pil5 = NULL;lv_obj_t *ui_Pil6 = NULL;lv_obj_t *ui_Pil7 = NULL;lv_obj_t *ui_Pil8 = NULL;lv_obj_t *ui_Pil10 = NULL;lv_obj_t *ui_Pil11 = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions
void ui_event_PokeBallAnalog( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Timer, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Timer_screen_init);
}
}

// build funtions

void ui_PokeBallAnalog_screen_init(void)
{
ui_PokeBallAnalog = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PokeBallAnalog, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Panel3, 533);
lv_obj_set_height( ui_Panel3, 224);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, -132 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xAC0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xAC0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Panel4, 506);
lv_obj_set_height( ui_Panel4, 226);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, 136 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Panel2, 517);
lv_obj_set_height( ui_Panel2, 50);
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Panel5, 150);
lv_obj_set_height( ui_Panel5, 150);
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel5, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel5, 17, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pil12 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil12, 24);
lv_obj_set_height( ui_Pil12, 45);
lv_obj_set_x( ui_Pil12, 0 );
lv_obj_set_y( ui_Pil12, -215 );
lv_obj_set_align( ui_Pil12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil12, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil12, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil1 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil1, 24);
lv_obj_set_height( ui_Pil1, 45);
lv_obj_set_x( ui_Pil1, 107 );
lv_obj_set_y( ui_Pil1, -186 );
lv_obj_set_align( ui_Pil1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil1, 300, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil1, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil1, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil2 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil2, 24);
lv_obj_set_height( ui_Pil2, 45);
lv_obj_set_x( ui_Pil2, 186 );
lv_obj_set_y( ui_Pil2, -107 );
lv_obj_set_align( ui_Pil2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil2, 600, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil2, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil2, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil4 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil4, 24);
lv_obj_set_height( ui_Pil4, 45);
lv_obj_set_x( ui_Pil4, 186 );
lv_obj_set_y( ui_Pil4, 107 );
lv_obj_set_align( ui_Pil4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil4, -600, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil4, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil4, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil4, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil4, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil5 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil5, 24);
lv_obj_set_height( ui_Pil5, 45);
lv_obj_set_x( ui_Pil5, 107 );
lv_obj_set_y( ui_Pil5, 186 );
lv_obj_set_align( ui_Pil5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil5, -300, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil5, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil5, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil5, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil5, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil6 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil6, 24);
lv_obj_set_height( ui_Pil6, 45);
lv_obj_set_x( ui_Pil6, 0 );
lv_obj_set_y( ui_Pil6, 215 );
lv_obj_set_align( ui_Pil6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil6, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil6, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil6, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil6, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil7 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil7, 24);
lv_obj_set_height( ui_Pil7, 45);
lv_obj_set_x( ui_Pil7, -107 );
lv_obj_set_y( ui_Pil7, 186 );
lv_obj_set_align( ui_Pil7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil7, 300, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil7, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil7, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil7, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil7, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil8 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil8, 24);
lv_obj_set_height( ui_Pil8, 45);
lv_obj_set_x( ui_Pil8, -186 );
lv_obj_set_y( ui_Pil8, 107 );
lv_obj_set_align( ui_Pil8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil8, 600, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil8, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil8, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil8, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil8, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil10 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil10, 24);
lv_obj_set_height( ui_Pil10, 45);
lv_obj_set_x( ui_Pil10, -186 );
lv_obj_set_y( ui_Pil10, -107 );
lv_obj_set_align( ui_Pil10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil10, -600, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil10, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil10, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil10, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil10, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Pil11 = lv_obj_create(ui_PokeBallAnalog);
lv_obj_set_width( ui_Pil11, 24);
lv_obj_set_height( ui_Pil11, 45);
lv_obj_set_x( ui_Pil11, -107 );
lv_obj_set_y( ui_Pil11, -186 );
lv_obj_set_align( ui_Pil11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Pil11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pil11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pil11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pil11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_Pil11, -300, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Pil11, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Pil11, 21, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Pil11, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pil11, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_PokeBallAnalog);
lv_img_set_src(ui_Image2, &ui_img_835555188);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 120
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 122
lv_obj_set_x( ui_Image2, -59 );
lv_obj_set_y( ui_Image2, -56 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_transform_angle(ui_Image2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_x(ui_Image2, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_pivot_y(ui_Image2, 120, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PokeBallAnalog, ui_event_PokeBallAnalog, LV_EVENT_ALL, NULL);

}

void ui_PokeBallAnalog_screen_destroy(void)
{
   if (ui_PokeBallAnalog) lv_obj_del(ui_PokeBallAnalog);

// NULL screen variables
ui_PokeBallAnalog= NULL;
ui_Panel3= NULL;
ui_Panel4= NULL;
ui_Panel2= NULL;
ui_Panel5= NULL;
ui_Pil12= NULL;
ui_Pil1= NULL;
ui_Pil2= NULL;
ui_Pil4= NULL;
ui_Pil5= NULL;
ui_Pil6= NULL;
ui_Pil7= NULL;
ui_Pil8= NULL;
ui_Pil10= NULL;
ui_Pil11= NULL;
ui_Image2= NULL;

}
