// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_PokeBallAnalog.h"
#include "ui_Screen1.h"
#include "ui_Analog.h"
#include "ui_Timer.h"
#include "ui_Settings.h"
#include "ui_Photo.h"
#include "ui_Photo2.h"
#include "ui_StopWatch.h"
#include "ui_Alarm.h"
#include "ui_Pet.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_835555188);   // assets/56-566269_28-collection-of-pikachu-tail-clipart.png
LV_IMG_DECLARE( ui_img_allyellow_png);   // assets/allYellow.png
LV_IMG_DECLARE( ui_img_pokeoutfits_png);   // assets/pokeOutfits.png

// FONTS
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Icons);
LV_FONT_DECLARE( ui_font_IconsLarge);
LV_FONT_DECLARE( ui_font_Poke30);
LV_FONT_DECLARE( ui_font_Poke90);
LV_FONT_DECLARE( ui_font_Pokemon);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
