// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Alarm = NULL;lv_obj_t *ui_Timers = NULL;lv_obj_t *ui_Timer1 = NULL;lv_obj_t *ui_DeleteTimer = NULL;lv_obj_t *ui_Label47 = NULL;lv_obj_t *ui_Label46 = NULL;lv_obj_t *ui_TimeLabel = NULL;lv_obj_t *ui_Timer2 = NULL;lv_obj_t *ui_DeleteTimer1 = NULL;lv_obj_t *ui_Label48 = NULL;lv_obj_t *ui_Label49 = NULL;lv_obj_t *ui_TimeLabel1 = NULL;lv_obj_t *ui_Timer3 = NULL;lv_obj_t *ui_DeleteTimer2 = NULL;lv_obj_t *ui_Label50 = NULL;lv_obj_t *ui_Label51 = NULL;lv_obj_t *ui_TimeLabel2 = NULL;lv_obj_t *ui_Timer4 = NULL;lv_obj_t *ui_DeleteTimer3 = NULL;lv_obj_t *ui_Label52 = NULL;lv_obj_t *ui_Label53 = NULL;lv_obj_t *ui_TimeLabel3 = NULL;lv_obj_t *ui_AddTimer = NULL;lv_obj_t *ui_Label45 = NULL;lv_obj_t *ui_TimerSetPopup = NULL;lv_obj_t *ui_Panel7 = NULL;lv_obj_t *ui_AlarmTime = NULL;lv_obj_t *ui_HourPlus = NULL;lv_obj_t *ui_Label54 = NULL;lv_obj_t *ui_HourMinus = NULL;lv_obj_t *ui_Label55 = NULL;lv_obj_t *ui_MinuteMinus = NULL;lv_obj_t *ui_Label56 = NULL;lv_obj_t *ui_MinuteMinus1 = NULL;lv_obj_t *ui_Label57 = NULL;lv_obj_t *ui_AMPMDropdown2 = NULL;lv_obj_t *ui_CancelButton = NULL;lv_obj_t *ui_Label58 = NULL;lv_obj_t *ui_AddButton = NULL;lv_obj_t *ui_Label59 = NULL;
// event funtions
void ui_event_Alarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Photo, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Photo_screen_init);
}
}

// build funtions

void ui_Alarm_screen_init(void)
{
ui_Alarm = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Alarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Alarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Default_Yellow);
ui_object_set_themeable_style_property(ui_Alarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Default_Yellow);

lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);
return;  // Alarm UI disabled — SquareLine output renders incorrectly. Stub only.

ui_Timers = lv_obj_create(ui_Alarm);
lv_obj_remove_style_all(ui_Timers);
lv_obj_set_width( ui_Timers, 384);
lv_obj_set_height( ui_Timers, 535);
lv_obj_set_x( ui_Timers, 0 );
lv_obj_set_y( ui_Timers, -31 );
lv_obj_set_align( ui_Timers, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Timers, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Timers, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Timer1 = lv_obj_create(ui_Timers);
lv_obj_set_width( ui_Timer1, 302);
lv_obj_set_height( ui_Timer1, 66);
lv_obj_set_x( ui_Timer1, 0 );
lv_obj_set_y( ui_Timer1, -100 );
lv_obj_set_align( ui_Timer1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Timer1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Timer1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Timer1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_DeleteTimer = lv_btn_create(ui_Timer1);
lv_obj_set_width( ui_DeleteTimer, 55);
lv_obj_set_height( ui_DeleteTimer, 55);
lv_obj_set_x( ui_DeleteTimer, 117 );
lv_obj_set_y( ui_DeleteTimer, 0 );
lv_obj_set_align( ui_DeleteTimer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DeleteTimer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DeleteTimer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DeleteTimer, lv_color_hex(0x950000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeleteTimer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label47 = lv_label_create(ui_DeleteTimer);
lv_obj_set_width( ui_Label47, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label47, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label47, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label47,"q");
lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label47, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label46 = lv_label_create(ui_Timer1);
lv_obj_set_width( ui_Label46, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label46, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label46, -118 );
lv_obj_set_y( ui_Label46, -2 );
lv_obj_set_align( ui_Label46, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label46,"r");
lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label46, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeLabel = lv_label_create(ui_Timer1);
lv_obj_set_width( ui_TimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeLabel,"No Timer");
lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Timer2 = lv_obj_create(ui_Timers);
lv_obj_set_width( ui_Timer2, 302);
lv_obj_set_height( ui_Timer2, 66);
lv_obj_set_x( ui_Timer2, 0 );
lv_obj_set_y( ui_Timer2, -25 );
lv_obj_set_align( ui_Timer2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Timer2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Timer2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Timer2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_DeleteTimer1 = lv_btn_create(ui_Timer2);
lv_obj_set_width( ui_DeleteTimer1, 55);
lv_obj_set_height( ui_DeleteTimer1, 55);
lv_obj_set_x( ui_DeleteTimer1, 117 );
lv_obj_set_y( ui_DeleteTimer1, 0 );
lv_obj_set_align( ui_DeleteTimer1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DeleteTimer1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DeleteTimer1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DeleteTimer1, lv_color_hex(0x950000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeleteTimer1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label48 = lv_label_create(ui_DeleteTimer1);
lv_obj_set_width( ui_Label48, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label48, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label48, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label48,"q");
lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label48, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label49 = lv_label_create(ui_Timer2);
lv_obj_set_width( ui_Label49, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label49, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label49, -118 );
lv_obj_set_y( ui_Label49, -2 );
lv_obj_set_align( ui_Label49, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label49,"r");
lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label49, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeLabel1 = lv_label_create(ui_Timer2);
lv_obj_set_width( ui_TimeLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimeLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeLabel1,"No Timer");
lv_obj_set_style_text_font(ui_TimeLabel1, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Timer3 = lv_obj_create(ui_Timers);
lv_obj_set_width( ui_Timer3, 302);
lv_obj_set_height( ui_Timer3, 66);
lv_obj_set_x( ui_Timer3, 0 );
lv_obj_set_y( ui_Timer3, 50 );
lv_obj_set_align( ui_Timer3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Timer3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Timer3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Timer3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_DeleteTimer2 = lv_btn_create(ui_Timer3);
lv_obj_set_width( ui_DeleteTimer2, 55);
lv_obj_set_height( ui_DeleteTimer2, 55);
lv_obj_set_x( ui_DeleteTimer2, 117 );
lv_obj_set_y( ui_DeleteTimer2, 0 );
lv_obj_set_align( ui_DeleteTimer2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DeleteTimer2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DeleteTimer2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DeleteTimer2, lv_color_hex(0x950000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeleteTimer2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label50 = lv_label_create(ui_DeleteTimer2);
lv_obj_set_width( ui_Label50, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label50, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label50, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label50,"q");
lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label50, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label51 = lv_label_create(ui_Timer3);
lv_obj_set_width( ui_Label51, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label51, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label51, -118 );
lv_obj_set_y( ui_Label51, -2 );
lv_obj_set_align( ui_Label51, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label51,"r");
lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label51, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeLabel2 = lv_label_create(ui_Timer3);
lv_obj_set_width( ui_TimeLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimeLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeLabel2,"No Timer");
lv_obj_set_style_text_font(ui_TimeLabel2, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Timer4 = lv_obj_create(ui_Timers);
lv_obj_set_width( ui_Timer4, 302);
lv_obj_set_height( ui_Timer4, 66);
lv_obj_set_x( ui_Timer4, 0 );
lv_obj_set_y( ui_Timer4, 125 );
lv_obj_set_align( ui_Timer4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Timer4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Timer4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Timer4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Timer4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_DeleteTimer3 = lv_btn_create(ui_Timer4);
lv_obj_set_width( ui_DeleteTimer3, 55);
lv_obj_set_height( ui_DeleteTimer3, 55);
lv_obj_set_x( ui_DeleteTimer3, 117 );
lv_obj_set_y( ui_DeleteTimer3, 0 );
lv_obj_set_align( ui_DeleteTimer3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DeleteTimer3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DeleteTimer3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DeleteTimer3, lv_color_hex(0x950000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeleteTimer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label52 = lv_label_create(ui_DeleteTimer3);
lv_obj_set_width( ui_Label52, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label52, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label52, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label52,"q");
lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label52, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label53 = lv_label_create(ui_Timer4);
lv_obj_set_width( ui_Label53, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label53, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label53, -118 );
lv_obj_set_y( ui_Label53, -2 );
lv_obj_set_align( ui_Label53, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label53,"r");
lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label53, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeLabel3 = lv_label_create(ui_Timer4);
lv_obj_set_width( ui_TimeLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimeLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeLabel3,"No Timer");
lv_obj_set_style_text_font(ui_TimeLabel3, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AddTimer = lv_btn_create(ui_Timers);
lv_obj_set_width( ui_AddTimer, 194);
lv_obj_set_height( ui_AddTimer, 79);
lv_obj_set_x( ui_AddTimer, 0 );
lv_obj_set_y( ui_AddTimer, 206 );
lv_obj_set_align( ui_AddTimer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AddTimer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AddTimer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_AddTimer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_AddTimer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);

ui_Label45 = lv_label_create(ui_AddTimer);
lv_obj_set_width( ui_Label45, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label45, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label45, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label45,"p");
lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label45, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimerSetPopup = lv_obj_create(ui_Alarm);
lv_obj_remove_style_all(ui_TimerSetPopup);
lv_obj_set_width( ui_TimerSetPopup, 402);
lv_obj_set_height( ui_TimerSetPopup, 422);
lv_obj_set_align( ui_TimerSetPopup, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TimerSetPopup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel7 = lv_obj_create(ui_TimerSetPopup);
lv_obj_set_width( ui_Panel7, 287);
lv_obj_set_height( ui_Panel7, 330);
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_AlarmTime = lv_label_create(ui_TimerSetPopup);
lv_obj_set_width( ui_AlarmTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlarmTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AlarmTime, 0 );
lv_obj_set_y( ui_AlarmTime, 0 );  // was -97, testing
lv_obj_set_align( ui_AlarmTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_AlarmTime,"00:00");
lv_obj_set_style_text_color(ui_AlarmTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AlarmTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AlarmTime, &ui_font_Poke90, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_flag(ui_TimerSetPopup, LV_OBJ_FLAG_HIDDEN);
lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);
return;  // TEST: popup + Panel7 + AlarmTime ONLY

ui_HourPlus = lv_btn_create(ui_TimerSetPopup);
lv_obj_set_width( ui_HourPlus, 40);
lv_obj_set_height( ui_HourPlus, 40);
lv_obj_set_x( ui_HourPlus, -99 );
lv_obj_set_y( ui_HourPlus, -36 );
lv_obj_set_align( ui_HourPlus, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HourPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HourPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HourPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HourPlus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label54 = lv_label_create(ui_HourPlus);
lv_obj_set_width( ui_Label54, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label54, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label54, 0 );
lv_obj_set_y( ui_Label54, 7 );
lv_obj_set_align( ui_Label54, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label54,"+");
ui_object_set_themeable_style_property(ui_Label54, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label54, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label54, &ui_font_Poke30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HourMinus = lv_btn_create(ui_TimerSetPopup);
lv_obj_set_width( ui_HourMinus, 40);
lv_obj_set_height( ui_HourMinus, 40);
lv_obj_set_x( ui_HourMinus, -51 );
lv_obj_set_y( ui_HourMinus, -36 );
lv_obj_set_align( ui_HourMinus, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HourMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HourMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HourMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HourMinus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label55 = lv_label_create(ui_HourMinus);
lv_obj_set_width( ui_Label55, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label55, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label55, 0 );
lv_obj_set_y( ui_Label55, 7 );
lv_obj_set_align( ui_Label55, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label55,"-");
ui_object_set_themeable_style_property(ui_Label55, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label55, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label55, &ui_font_Poke30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinuteMinus = lv_btn_create(ui_TimerSetPopup);
lv_obj_set_width( ui_MinuteMinus, 40);
lv_obj_set_height( ui_MinuteMinus, 40);
lv_obj_set_x( ui_MinuteMinus, 99 );
lv_obj_set_y( ui_MinuteMinus, -34 );
lv_obj_set_align( ui_MinuteMinus, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MinuteMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MinuteMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MinuteMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MinuteMinus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label56 = lv_label_create(ui_MinuteMinus);
lv_obj_set_width( ui_Label56, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label56, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label56, 0 );
lv_obj_set_y( ui_Label56, 7 );
lv_obj_set_align( ui_Label56, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label56,"-");
ui_object_set_themeable_style_property(ui_Label56, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label56, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label56, &ui_font_Poke30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinuteMinus1 = lv_btn_create(ui_TimerSetPopup);
lv_obj_set_width( ui_MinuteMinus1, 40);
lv_obj_set_height( ui_MinuteMinus1, 40);
lv_obj_set_x( ui_MinuteMinus1, 51 );
lv_obj_set_y( ui_MinuteMinus1, -34 );
lv_obj_set_align( ui_MinuteMinus1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MinuteMinus1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MinuteMinus1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MinuteMinus1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MinuteMinus1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label57 = lv_label_create(ui_MinuteMinus1);
lv_obj_set_width( ui_Label57, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label57, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label57, 0 );
lv_obj_set_y( ui_Label57, 7 );
lv_obj_set_align( ui_Label57, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label57,"+");
ui_object_set_themeable_style_property(ui_Label57, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label57, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label57, &ui_font_Poke30, LV_PART_MAIN| LV_STATE_DEFAULT);

if (0) { // skip dropdown + Cancel + Add — these crash the device
ui_AMPMDropdown2 = lv_dropdown_create(ui_TimerSetPopup);
lv_dropdown_set_options( ui_AMPMDropdown2, "AM\nPM" );
lv_obj_set_width( ui_AMPMDropdown2, 240);
lv_obj_set_height( ui_AMPMDropdown2, LV_SIZE_CONTENT);
lv_obj_set_x( ui_AMPMDropdown2, 0 );
lv_obj_set_y( ui_AMPMDropdown2, 20 );
lv_obj_set_align( ui_AMPMDropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AMPMDropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );
ui_object_set_themeable_style_property(ui_AMPMDropdown2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_AMPMDropdown2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_bg_color(ui_AMPMDropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AMPMDropdown2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AMPMDropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AMPMDropdown2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_AMPMDropdown2), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_AMPMDropdown2), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_AMPMDropdown2), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_AMPMDropdown2), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_AMPMDropdown2), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_AMPMDropdown2), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_CancelButton = lv_btn_create(ui_TimerSetPopup);
lv_obj_set_width( ui_CancelButton, 115);
lv_obj_set_height( ui_CancelButton, 82);
lv_obj_set_x( ui_CancelButton, -60 );
lv_obj_set_y( ui_CancelButton, 101 );
lv_obj_set_align( ui_CancelButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CancelButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CancelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label58 = lv_label_create(ui_CancelButton);
lv_obj_set_width( ui_Label58, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label58, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label58, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label58,"Cancel");
ui_object_set_themeable_style_property(ui_Label58, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label58, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AddButton = lv_btn_create(ui_TimerSetPopup);
lv_obj_set_width( ui_AddButton, 115);
lv_obj_set_height( ui_AddButton, 82);
lv_obj_set_x( ui_AddButton, 60 );
lv_obj_set_y( ui_AddButton, 101 );
lv_obj_set_align( ui_AddButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AddButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AddButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AddButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AddButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label59 = lv_label_create(ui_AddButton);
lv_obj_set_width( ui_Label59, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label59, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label59, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label59,"Add");
ui_object_set_themeable_style_property(ui_Label59, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label59, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
} else { ui_AMPMDropdown2 = NULL; ui_CancelButton = NULL; ui_AddButton = NULL; ui_Label58 = NULL; ui_Label59 = NULL; }

lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);

// Hide popup permanently — SquareLine output renders the popup contents incorrectly,
// causing artifacts on other screens. Alarms are added via cycling on the AddTimer button.
lv_obj_add_flag(ui_TimerSetPopup, LV_OBJ_FLAG_HIDDEN);
// (alarm list container stays hidden — will be shown lazily once user adds an alarm)

}

void ui_Alarm_screen_destroy(void)
{
   if (ui_Alarm) lv_obj_del(ui_Alarm);

// NULL screen variables
ui_Alarm= NULL;
ui_Timers= NULL;
ui_Timer1= NULL;
ui_DeleteTimer= NULL;
ui_Label47= NULL;
ui_Label46= NULL;
ui_TimeLabel= NULL;
ui_Timer2= NULL;
ui_DeleteTimer1= NULL;
ui_Label48= NULL;
ui_Label49= NULL;
ui_TimeLabel1= NULL;
ui_Timer3= NULL;
ui_DeleteTimer2= NULL;
ui_Label50= NULL;
ui_Label51= NULL;
ui_TimeLabel2= NULL;
ui_Timer4= NULL;
ui_DeleteTimer3= NULL;
ui_Label52= NULL;
ui_Label53= NULL;
ui_TimeLabel3= NULL;
ui_AddTimer= NULL;
ui_Label45= NULL;
ui_TimerSetPopup= NULL;
ui_Panel7= NULL;
ui_AlarmTime= NULL;
ui_HourPlus= NULL;
ui_Label54= NULL;
ui_HourMinus= NULL;
ui_Label55= NULL;
ui_MinuteMinus= NULL;
ui_Label56= NULL;
ui_MinuteMinus1= NULL;
ui_Label57= NULL;
ui_AMPMDropdown2= NULL;
ui_CancelButton= NULL;
ui_Label58= NULL;
ui_AddButton= NULL;
ui_Label59= NULL;

}
