// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ALARM_H
#define UI_ALARM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Alarm
extern void ui_Alarm_screen_init(void);
extern void ui_Alarm_screen_destroy(void);
extern lv_obj_t *ui_Alarm;
extern lv_obj_t *ui_AlarmContainer;
extern lv_obj_t *ui_Alarm1;
extern lv_obj_t *ui_Label46;
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Label47;
extern lv_obj_t *ui_Label48;
extern lv_obj_t *ui_Label55;
extern lv_obj_t *ui_Alarm2;
extern lv_obj_t *ui_Label49;
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Label50;
extern lv_obj_t *ui_Label51;
extern lv_obj_t *ui_Label58;
extern lv_obj_t *ui_Alarm3;
extern lv_obj_t *ui_Label52;
extern lv_obj_t *ui_Button13;
extern lv_obj_t *ui_Label53;
extern lv_obj_t *ui_Label54;
extern lv_obj_t *ui_Label57;
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label45;
extern lv_obj_t *ui_AlarmSetContainer;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label60;
extern lv_obj_t *ui_Button15;
extern lv_obj_t *ui_Label61;
extern lv_obj_t *ui_Button14;
extern lv_obj_t *ui_Label59;
extern lv_obj_t *ui_Button16;
extern lv_obj_t *ui_Label62;
extern lv_obj_t *ui_Button17;
extern lv_obj_t *ui_Label63;
extern lv_obj_t *ui_Button18;
extern lv_obj_t *ui_Label56;
extern lv_obj_t *ui_Button19;
extern lv_obj_t *ui_Label64;
extern lv_obj_t *ui_Dropdown2;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

