// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ALARM_H
#define UI_ALARM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Alarm
extern void ui_Alarm_screen_init(void);
extern void ui_Alarm_screen_destroy(void);
extern void ui_event_Alarm( lv_event_t * e);
extern lv_obj_t *ui_Alarm;
extern lv_obj_t *ui_Timers;
extern lv_obj_t *ui_Timer1;
extern lv_obj_t *ui_DeleteTimer;
extern lv_obj_t *ui_Label47;
extern lv_obj_t *ui_Label46;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_Timer2;
extern lv_obj_t *ui_DeleteTimer1;
extern lv_obj_t *ui_Label48;
extern lv_obj_t *ui_Label49;
extern lv_obj_t *ui_TimeLabel1;
extern lv_obj_t *ui_Timer3;
extern lv_obj_t *ui_DeleteTimer2;
extern lv_obj_t *ui_Label50;
extern lv_obj_t *ui_Label51;
extern lv_obj_t *ui_TimeLabel2;
extern lv_obj_t *ui_Timer4;
extern lv_obj_t *ui_DeleteTimer3;
extern lv_obj_t *ui_Label52;
extern lv_obj_t *ui_Label53;
extern lv_obj_t *ui_TimeLabel3;
extern lv_obj_t *ui_AddTimer;
extern lv_obj_t *ui_Label45;
extern lv_obj_t *ui_TimerSetPopup;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_AlarmTime;
extern lv_obj_t *ui_HourPlus;
extern lv_obj_t *ui_Label54;
extern lv_obj_t *ui_HourMinus;
extern lv_obj_t *ui_Label55;
extern lv_obj_t *ui_MinuteMinus;
extern lv_obj_t *ui_Label56;
extern lv_obj_t *ui_MinuteMinus1;
extern lv_obj_t *ui_Label57;
extern lv_obj_t *ui_AMPMDropdown2;
extern lv_obj_t *ui_CancelButton;
extern lv_obj_t *ui_Label58;
extern lv_obj_t *ui_AddButton;
extern lv_obj_t *ui_Label59;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

