// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Alarm = NULL;lv_obj_t *ui_AlarmContainer = NULL;lv_obj_t *ui_Alarm1 = NULL;lv_obj_t *ui_Label46 = NULL;lv_obj_t *ui_Button11 = NULL;lv_obj_t *ui_Label47 = NULL;lv_obj_t *ui_Label48 = NULL;lv_obj_t *ui_Label55 = NULL;lv_obj_t *ui_Alarm2 = NULL;lv_obj_t *ui_Label49 = NULL;lv_obj_t *ui_Button12 = NULL;lv_obj_t *ui_Label50 = NULL;lv_obj_t *ui_Label51 = NULL;lv_obj_t *ui_Label58 = NULL;lv_obj_t *ui_Alarm3 = NULL;lv_obj_t *ui_Label52 = NULL;lv_obj_t *ui_Button13 = NULL;lv_obj_t *ui_Label53 = NULL;lv_obj_t *ui_Label54 = NULL;lv_obj_t *ui_Label57 = NULL;lv_obj_t *ui_Button8 = NULL;lv_obj_t *ui_Label45 = NULL;lv_obj_t *ui_AlarmSetContainer = NULL;lv_obj_t *ui_Panel7 = NULL;lv_obj_t *ui_Label60 = NULL;lv_obj_t *ui_Button15 = NULL;lv_obj_t *ui_Label61 = NULL;lv_obj_t *ui_Button14 = NULL;lv_obj_t *ui_Label59 = NULL;lv_obj_t *ui_Button16 = NULL;lv_obj_t *ui_Label62 = NULL;lv_obj_t *ui_Button17 = NULL;lv_obj_t *ui_Label63 = NULL;lv_obj_t *ui_Button18 = NULL;lv_obj_t *ui_Label56 = NULL;lv_obj_t *ui_Button19 = NULL;lv_obj_t *ui_Label64 = NULL;lv_obj_t *ui_Dropdown2 = NULL;lv_obj_t *ui_TextArea1 = NULL;lv_obj_t *ui_Keyboard1 = NULL;
// event funtions

// build funtions

void ui_Alarm_screen_init(void)
{
ui_Alarm = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Alarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Alarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Default_Yellow);
ui_object_set_themeable_style_property(ui_Alarm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Default_Yellow);

ui_AlarmContainer = lv_obj_create(ui_Alarm);
lv_obj_remove_style_all(ui_AlarmContainer);
lv_obj_set_width( ui_AlarmContainer, 391);
lv_obj_set_height( ui_AlarmContainer, 446);
lv_obj_set_x( ui_AlarmContainer, -1 );
lv_obj_set_y( ui_AlarmContainer, -35 );
lv_obj_set_align( ui_AlarmContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AlarmContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_AlarmContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_AlarmContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_AlarmContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_Alarm1 = lv_obj_create(ui_AlarmContainer);
lv_obj_set_width( ui_Alarm1, 361);
lv_obj_set_height( ui_Alarm1, 69);
lv_obj_set_x( ui_Alarm1, 0 );
lv_obj_set_y( ui_Alarm1, -69 );
lv_obj_set_align( ui_Alarm1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Alarm1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Alarm1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Alarm1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Alarm1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Alarm1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_Label46 = lv_label_create(ui_Alarm1);
lv_obj_set_width( ui_Label46, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label46, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label46, -145 );
lv_obj_set_y( ui_Label46, 0 );
lv_obj_set_align( ui_Label46, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label46,"r");
lv_obj_set_style_text_font(ui_Label46, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button11 = lv_btn_create(ui_Alarm1);
lv_obj_set_width( ui_Button11, 60);
lv_obj_set_height( ui_Button11, 60);
lv_obj_set_x( ui_Button11, 145 );
lv_obj_set_y( ui_Button11, 0 );
lv_obj_set_align( ui_Button11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x9E0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label47 = lv_label_create(ui_Button11);
lv_obj_set_width( ui_Label47, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label47, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label47, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label47,"q");
lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label47, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label48 = lv_label_create(ui_Alarm1);
lv_obj_set_width( ui_Label48, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label48, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label48, 0 );
lv_obj_set_y( ui_Label48, 19 );
lv_obj_set_align( ui_Label48, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label48,"00:25 PM");
lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label55 = lv_label_create(ui_Alarm1);
lv_obj_set_width( ui_Label55, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label55, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label55, 0 );
lv_obj_set_y( ui_Label55, -14 );
lv_obj_set_align( ui_Label55, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label55,"Label 1");
lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alarm2 = lv_obj_create(ui_AlarmContainer);
lv_obj_set_width( ui_Alarm2, 361);
lv_obj_set_height( ui_Alarm2, 69);
lv_obj_set_x( ui_Alarm2, 0 );
lv_obj_set_y( ui_Alarm2, 9 );
lv_obj_set_align( ui_Alarm2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Alarm2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Alarm2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Alarm2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Alarm2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Alarm2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_Label49 = lv_label_create(ui_Alarm2);
lv_obj_set_width( ui_Label49, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label49, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label49, -145 );
lv_obj_set_y( ui_Label49, 0 );
lv_obj_set_align( ui_Label49, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label49,"r");
lv_obj_set_style_text_font(ui_Label49, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button12 = lv_btn_create(ui_Alarm2);
lv_obj_set_width( ui_Button12, 60);
lv_obj_set_height( ui_Button12, 60);
lv_obj_set_x( ui_Button12, 145 );
lv_obj_set_y( ui_Button12, 0 );
lv_obj_set_align( ui_Button12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x9E0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label50 = lv_label_create(ui_Button12);
lv_obj_set_width( ui_Label50, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label50, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label50, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label50,"q");
lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label50, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label51 = lv_label_create(ui_Alarm2);
lv_obj_set_width( ui_Label51, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label51, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label51, 0 );
lv_obj_set_y( ui_Label51, 19 );
lv_obj_set_align( ui_Label51, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label51,"00:25 PM");
lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label58 = lv_label_create(ui_Alarm2);
lv_obj_set_width( ui_Label58, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label58, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label58, 0 );
lv_obj_set_y( ui_Label58, -14 );
lv_obj_set_align( ui_Label58, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label58,"Label 2");
lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alarm3 = lv_obj_create(ui_AlarmContainer);
lv_obj_set_width( ui_Alarm3, 361);
lv_obj_set_height( ui_Alarm3, 69);
lv_obj_set_x( ui_Alarm3, 0 );
lv_obj_set_y( ui_Alarm3, 86 );
lv_obj_set_align( ui_Alarm3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Alarm3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Alarm3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Alarm3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Alarm3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Alarm3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_Label52 = lv_label_create(ui_Alarm3);
lv_obj_set_width( ui_Label52, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label52, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label52, -145 );
lv_obj_set_y( ui_Label52, 0 );
lv_obj_set_align( ui_Label52, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label52,"r");
lv_obj_set_style_text_font(ui_Label52, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button13 = lv_btn_create(ui_Alarm3);
lv_obj_set_width( ui_Button13, 60);
lv_obj_set_height( ui_Button13, 60);
lv_obj_set_x( ui_Button13, 145 );
lv_obj_set_y( ui_Button13, 0 );
lv_obj_set_align( ui_Button13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x9E0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label53 = lv_label_create(ui_Button13);
lv_obj_set_width( ui_Label53, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label53, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label53, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label53,"q");
lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label53, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label54 = lv_label_create(ui_Alarm3);
lv_obj_set_width( ui_Label54, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label54, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label54, 0 );
lv_obj_set_y( ui_Label54, 19 );
lv_obj_set_align( ui_Label54, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label54,"00:25 PM");
lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label57 = lv_label_create(ui_Alarm3);
lv_obj_set_width( ui_Label57, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label57, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label57, 0 );
lv_obj_set_y( ui_Label57, -14 );
lv_obj_set_align( ui_Label57, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label57,"Label 3");
lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button8 = lv_btn_create(ui_AlarmContainer);
lv_obj_set_width( ui_Button8, 194);
lv_obj_set_height( ui_Button8, 79);
lv_obj_set_x( ui_Button8, 0 );
lv_obj_set_y( ui_Button8, 174 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Button8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Button8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);

ui_Label45 = lv_label_create(ui_Button8);
lv_obj_set_width( ui_Label45, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label45, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label45, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label45,"p");
lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label45, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlarmSetContainer = lv_obj_create(ui_Alarm);
lv_obj_remove_style_all(ui_AlarmSetContainer);
lv_obj_set_width( ui_AlarmSetContainer, 375);
lv_obj_set_height( ui_AlarmSetContainer, 357);
lv_obj_set_x( ui_AlarmSetContainer, 0 );
lv_obj_set_y( ui_AlarmSetContainer, -1 );
lv_obj_set_align( ui_AlarmSetContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AlarmSetContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel7 = lv_obj_create(ui_AlarmSetContainer);
lv_obj_set_width( ui_Panel7, 346);
lv_obj_set_height( ui_Panel7, 319);
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Red);

ui_Label60 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label60, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label60, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label60, 0 );
lv_obj_set_y( ui_Label60, -77 );
lv_obj_set_align( ui_Label60, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label60,"00:25");
lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label60, &ui_font_Poke90, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(ui_Label60, 256, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button15 = lv_btn_create(ui_Panel7);
lv_obj_set_width( ui_Button15, 53);
lv_obj_set_height( ui_Button15, 37);
lv_obj_set_x( ui_Button15, -108 );
lv_obj_set_y( ui_Button15, -15 );
lv_obj_set_align( ui_Button15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button15, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label61 = lv_label_create(ui_Button15);
lv_obj_set_width( ui_Label61, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label61, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label61, 0 );
lv_obj_set_y( ui_Label61, 5 );
lv_obj_set_align( ui_Label61, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label61,"+");
ui_object_set_themeable_style_property(ui_Label61, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label61, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label61, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button14 = lv_btn_create(ui_Panel7);
lv_obj_set_width( ui_Button14, 53);
lv_obj_set_height( ui_Button14, 37);
lv_obj_set_x( ui_Button14, -50 );
lv_obj_set_y( ui_Button14, -15 );
lv_obj_set_align( ui_Button14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button14, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label59 = lv_label_create(ui_Button14);
lv_obj_set_width( ui_Label59, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label59, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label59, 0 );
lv_obj_set_y( ui_Label59, 5 );
lv_obj_set_align( ui_Label59, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label59,"-");
ui_object_set_themeable_style_property(ui_Label59, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label59, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label59, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button16 = lv_btn_create(ui_Panel7);
lv_obj_set_width( ui_Button16, 53);
lv_obj_set_height( ui_Button16, 37);
lv_obj_set_x( ui_Button16, 50 );
lv_obj_set_y( ui_Button16, -15 );
lv_obj_set_align( ui_Button16, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button16, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label62 = lv_label_create(ui_Button16);
lv_obj_set_width( ui_Label62, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label62, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label62, 0 );
lv_obj_set_y( ui_Label62, 5 );
lv_obj_set_align( ui_Label62, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label62,"+");
ui_object_set_themeable_style_property(ui_Label62, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label62, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label62, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button17 = lv_btn_create(ui_Panel7);
lv_obj_set_width( ui_Button17, 53);
lv_obj_set_height( ui_Button17, 37);
lv_obj_set_x( ui_Button17, 108 );
lv_obj_set_y( ui_Button17, -15 );
lv_obj_set_align( ui_Button17, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button17, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label63 = lv_label_create(ui_Button17);
lv_obj_set_width( ui_Label63, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label63, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label63, 0 );
lv_obj_set_y( ui_Label63, 5 );
lv_obj_set_align( ui_Label63, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label63,"-");
ui_object_set_themeable_style_property(ui_Label63, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label63, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label63, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button18 = lv_btn_create(ui_AlarmSetContainer);
lv_obj_set_width( ui_Button18, 151);
lv_obj_set_height( ui_Button18, 50);
lv_obj_set_x( ui_Button18, -81 );
lv_obj_set_y( ui_Button18, 119 );
lv_obj_set_align( ui_Button18, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label56 = lv_label_create(ui_Button18);
lv_obj_set_width( ui_Label56, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label56, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label56, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label56,"Exit");
ui_object_set_themeable_style_property(ui_Label56, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label56, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button19 = lv_btn_create(ui_AlarmSetContainer);
lv_obj_set_width( ui_Button19, 151);
lv_obj_set_height( ui_Button19, 50);
lv_obj_set_x( ui_Button19, 81 );
lv_obj_set_y( ui_Button19, 119 );
lv_obj_set_align( ui_Button19, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button19, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label64 = lv_label_create(ui_Button19);
lv_obj_set_width( ui_Label64, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label64, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label64, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label64,"Add");
ui_object_set_themeable_style_property(ui_Label64, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Label64, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_Label64, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown2 = lv_dropdown_create(ui_AlarmSetContainer);
lv_dropdown_set_options( ui_Dropdown2, "AM\nPM\nOption 3" );
lv_obj_set_width( ui_Dropdown2, 150);
lv_obj_set_height( ui_Dropdown2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown2, -81 );
lv_obj_set_y( ui_Dropdown2, 50 );
lv_obj_set_align( ui_Dropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
ui_object_set_themeable_style_property(ui_Dropdown2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Dropdown2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_bg_color(ui_Dropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Dropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Dropdown2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea1 = lv_textarea_create(ui_AlarmSetContainer);
lv_obj_set_width( ui_TextArea1, 150);
lv_obj_set_height( ui_TextArea1, 40);
lv_obj_set_x( ui_TextArea1, 81 );
lv_obj_set_y( ui_TextArea1, 50 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Label");
lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFF0000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_Alarm);
lv_obj_set_width( ui_Keyboard1, 428);
lv_obj_set_height( ui_Keyboard1, 240);
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

}

void ui_Alarm_screen_destroy(void)
{
   if (ui_Alarm) lv_obj_del(ui_Alarm);

// NULL screen variables
ui_Alarm= NULL;
ui_AlarmContainer= NULL;
ui_Alarm1= NULL;
ui_Label46= NULL;
ui_Button11= NULL;
ui_Label47= NULL;
ui_Label48= NULL;
ui_Label55= NULL;
ui_Alarm2= NULL;
ui_Label49= NULL;
ui_Button12= NULL;
ui_Label50= NULL;
ui_Label51= NULL;
ui_Label58= NULL;
ui_Alarm3= NULL;
ui_Label52= NULL;
ui_Button13= NULL;
ui_Label53= NULL;
ui_Label54= NULL;
ui_Label57= NULL;
ui_Button8= NULL;
ui_Label45= NULL;
ui_AlarmSetContainer= NULL;
ui_Panel7= NULL;
ui_Label60= NULL;
ui_Button15= NULL;
ui_Label61= NULL;
ui_Button14= NULL;
ui_Label59= NULL;
ui_Button16= NULL;
ui_Label62= NULL;
ui_Button17= NULL;
ui_Label63= NULL;
ui_Button18= NULL;
ui_Label56= NULL;
ui_Button19= NULL;
ui_Label64= NULL;
ui_Dropdown2= NULL;
ui_TextArea1= NULL;
ui_Keyboard1= NULL;

}
