// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Photo = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Label25 = NULL;
// event funtions
void ui_event_Photo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Analog, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Analog_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Photo2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Photo2_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Settings_screen_init);
}
// Alarm screen removed — swipe-down gesture disabled
}

// build funtions

void ui_Photo_screen_init(void)
{
ui_Photo = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Photo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Photo, lv_color_hex(0x44444A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Photo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Photo, &ui_font_Pokemon, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Photo, lv_color_hex(0x515052), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Photo, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_Photo);
lv_img_set_src(ui_Image6, &ui_img_allyellow_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 466
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 466
lv_obj_set_x( ui_Image6, 1 );
lv_obj_set_y( ui_Image6, 44 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image6,280);

ui_Label25 = lv_label_create(ui_Photo);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, 0 );
lv_obj_set_y( ui_Label25, -138 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"00:25");
ui_object_set_themeable_style_property(ui_Label25, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Default_Yellow);
ui_object_set_themeable_style_property(ui_Label25, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Default_Yellow);
lv_obj_set_style_text_font(ui_Label25, &ui_font_Poke90, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Photo, ui_event_Photo, LV_EVENT_ALL, NULL);

}

void ui_Photo_screen_destroy(void)
{
   if (ui_Photo) lv_obj_del(ui_Photo);

// NULL screen variables
ui_Photo= NULL;
ui_Image6= NULL;
ui_Label25= NULL;

}
