// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Photo2 = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_Label21 = NULL;lv_obj_t *ui_Label27 = NULL;
// event funtions
void ui_event_Photo2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Photo, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Photo_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Timer, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Timer_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_PokeBallAnalog, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PokeBallAnalog_screen_init);
}
}

// build funtions

void ui_Photo2_screen_init(void)
{
ui_Photo2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Photo2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image7 = lv_img_create(ui_Photo2);
lv_img_set_src(ui_Image7, &ui_img_pokeoutfits_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 466
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 466
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image7,270);

ui_Label21 = lv_label_create(ui_Photo2);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label21, 0 );
lv_obj_set_y( ui_Label21, 102 );
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"Sunday, April 9th, 2026");
lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label21, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_Photo2);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"00:25");
lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label27, 220, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label27, &ui_font_Pokemon, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Photo2, ui_event_Photo2, LV_EVENT_ALL, NULL);

}

void ui_Photo2_screen_destroy(void)
{
   if (ui_Photo2) lv_obj_del(ui_Photo2);

// NULL screen variables
ui_Photo2= NULL;
ui_Image7= NULL;
ui_Label21= NULL;
ui_Label27= NULL;

}
