// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_POKEBALLANALOG_H
#define UI_POKEBALLANALOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PokeBallAnalog
extern void ui_PokeBallAnalog_screen_init(void);
extern void ui_PokeBallAnalog_screen_destroy(void);
extern void ui_event_PokeBallAnalog( lv_event_t * e);
extern lv_obj_t *ui_PokeBallAnalog;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Pil12;
extern lv_obj_t *ui_Pil1;
extern lv_obj_t *ui_Pil2;
extern lv_obj_t *ui_Pil4;
extern lv_obj_t *ui_Pil5;
extern lv_obj_t *ui_Pil6;
extern lv_obj_t *ui_Pil7;
extern lv_obj_t *ui_Pil8;
extern lv_obj_t *ui_Pil10;
extern lv_obj_t *ui_Pil11;
extern lv_obj_t *ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

