// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PHOTO2_H
#define UI_PHOTO2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Photo2
extern void ui_Photo2_screen_init(void);
extern void ui_Photo2_screen_destroy(void);
extern void ui_event_Photo2( lv_event_t * e);
extern lv_obj_t *ui_Photo2;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Label27;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

