// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PHOTO_H
#define UI_PHOTO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Photo
extern void ui_Photo_screen_init(void);
extern void ui_Photo_screen_destroy(void);
extern void ui_event_Photo( lv_event_t * e);
extern lv_obj_t *ui_Photo;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Label25;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

