// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STOPWATCH_H
#define UI_STOPWATCH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StopWatch
extern void ui_StopWatch_screen_init(void);
extern void ui_StopWatch_screen_destroy(void);
extern void ui_event_StopWatch( lv_event_t * e);
extern lv_obj_t *ui_StopWatch;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_PausePlay;
extern lv_obj_t *ui_Label42;
extern lv_obj_t *ui_Reset;
extern lv_obj_t *ui_Label44;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

