// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_StopWatch = NULL;lv_obj_t *ui_Label43 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_Label42 = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Label44 = NULL;
// event funtions

// build funtions

void ui_StopWatch_screen_init(void)
{
ui_StopWatch = lv_obj_create(NULL);
lv_obj_clear_flag( ui_StopWatch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_StopWatch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Default_Yellow);
ui_object_set_themeable_style_property(ui_StopWatch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Default_Yellow);

ui_Label43 = lv_label_create(ui_StopWatch);
lv_obj_set_width( ui_Label43, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label43, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label43, 0 );
lv_obj_set_y( ui_Label43, -32 );
lv_obj_set_align( ui_Label43, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label43,"00:00:00");
lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xE30B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label43, &ui_font_Poke90, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(ui_Label43, 256, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_StopWatch);
lv_obj_set_width( ui_Button4, 128);
lv_obj_set_height( ui_Button4, 119);
lv_obj_set_x( ui_Button4, -67 );
lv_obj_set_y( ui_Button4, 95 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Button4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Button4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);

ui_Label42 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label42, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label42, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label42, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label42,"h");
lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label42, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button7 = lv_btn_create(ui_StopWatch);
lv_obj_set_width( ui_Button7, 128);
lv_obj_set_height( ui_Button7, 119);
lv_obj_set_x( ui_Button7, 67 );
lv_obj_set_y( ui_Button7, 95 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);

ui_Label44 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label44, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label44, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label44, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label44,"i");
lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label44, &ui_font_IconsLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_StopWatch_screen_destroy(void)
{
   if (ui_StopWatch) lv_obj_del(ui_StopWatch);

// NULL screen variables
ui_StopWatch= NULL;
ui_Label43= NULL;
ui_Button4= NULL;
ui_Label42= NULL;
ui_Button7= NULL;
ui_Label44= NULL;

}
